version: '3'

services:
  frontend:
    build:
      context: ./frontend-microservice
    ports:
      - "8080:8080"

  catalog:
    build:
      context: ./catalog-microservice
    ports:
      - "8000:8000"

  orders:
    build:
      context: ./orders-microservice
    ports:
      - "8001:8001"
