version: '3'

services:
  frontend:
    build:
      context: ./frontend-microservice
    ports:
      - "8080:8080"
    networks:
      - app-network

  catalog:
        build:
          context: ./catalog-microservice
        ports:
          - "8000:8000"
        networks:
          - app-network

  orders:
        build:
          context: ./orders-microservice
        ports:
          - "8001:8001"
        networks:
          - app-network

networks:
      app-network:
        driver: bridge